repos:
-   repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
    - id: black
      language_version: python3.13
-   repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
        language_version: python3.13
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.3
    hooks:
    -   id: autoflake
        language_version: python3.13
        args: [--remove-all-unused-imports, --in-place, --ignore-init-module-imports]