"""create news page table

Revision ID: 610881d6096c
Revises:
Create Date: 2026-08-02 16:58:45.567200

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "610881d6096c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "newspage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "news_paper_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("date_published", sa.DateTime(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("newspage")
    # ### end Alembic commands ###
