"""Add field to track article json

Revision ID: 7654d934a365
Revises: 4b2251f4fc1b
Create Date: 2026-08-08 12:57:46.186867

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7654d934a365"
down_revision: Union[str, Sequence[str], None] = "4b2251f4fc1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "newspage",
        sa.Column(
            "article_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("newspage", "article_json")
    # ### end Alembic commands ###
