"""Add tweets table

Revision ID: 77f5e73e8fd0
Revises: 7654d934a365
Create Date: 2026-08-10 15:52:20.257561

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "77f5e73e8fd0"
down_revision: Union[str, Sequence[str], None] = "7654d934a365"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tweets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tweet_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("twitter_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("retweet_count", sa.Integer(), nullable=False),
        sa.Column("reply_count", sa.Integer(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("quote_count", sa.Integer(), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("lang", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("bookmark_count", sa.Integer(), nullable=False),
        sa.Column("is_reply", sa.Boolean(), nullable=False),
        sa.Column("in_reply_to_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("conversation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "in_reply_to_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "in_reply_to_username", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("author", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("card", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("place", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("hashtags", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_mentions", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "quoted_tweet", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "retweeted_tweet", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_limited_reply", sa.Boolean(), nullable=False),
        sa.Column(
            "community_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("article", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tweet_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tweets")
    # ### end Alembic commands ###
