"""Add categories table

Revision ID: b4adc78485bc
Revises: 77f5e73e8fd0
Create Date: 2026-08-11 11:49:36.282262

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4adc78485bc"
down_revision: Union[str, Sequence[str], None] = "77f5e73e8fd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("examples", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("tweets", sa.Column("category", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "tweets", "categories", ["category"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tweets", type_="foreignkey")
    op.drop_column("tweets", "category")
    op.drop_table("categories")
    # ### end Alembic commands ###
