"""base migration

Revision ID: e753e4a947f7
Revises:
Create Date: 2026-08-11 17:54:31.705422

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e753e4a947f7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("examples", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_categories_name")),
    )
    op.create_table(
        "newspage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "news_paper_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("date_published", sa.DateTime(), nullable=False),
        sa.Column(
            "article_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_newspage")),
    )
    op.create_table(
        "tweets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tweet_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("twitter_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("retweet_count", sa.Integer(), nullable=False),
        sa.Column("reply_count", sa.Integer(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("quote_count", sa.Integer(), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("lang", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("bookmark_count", sa.Integer(), nullable=False),
        sa.Column("is_reply", sa.Boolean(), nullable=False),
        sa.Column("in_reply_to_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("conversation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "in_reply_to_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "in_reply_to_username", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("author", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("card", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("place", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("hashtags", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_mentions", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "quoted_tweet", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "retweeted_tweet", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_limited_reply", sa.Boolean(), nullable=False),
        sa.Column(
            "community_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("article", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("category", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category"], ["categories.id"], name=op.f("fk_tweets_category_categories")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tweets")),
        sa.UniqueConstraint("tweet_id", name=op.f("uq_tweets_tweet_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tweets")
    op.drop_table("newspage")
    op.drop_table("categories")
    # ### end Alembic commands ###
